apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalog-api
  namespace: fcg-observability
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: catalog-api
  namespaceSelector:
    matchNames:
      - fcg-services
  endpoints:
    - port: http
      path: /metrics
      interval: 15s