apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-api
  name: user-api
  namespace: fcg-services
spec:
  selector:
    app: user-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
