apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-ingress
  namespace: fcg-services
  annotations:
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:

      - path: /api/User
        pathType: Prefix
        backend:
          service:
            name: user-api
            port:
              number: 80

      - path: /api/Auth
        pathType: Prefix
        backend:
          service:
            name: user-api
            port:
              number: 80