apiVersion: v1
kind: Secret
metadata:
  name: services-secrets
  namespace: fcg-services
type: Opaque
stringData:
  saPassword: "Olszewski@123"
  rabbitMQDefaultUser: "FiapAdmin"
  rabbitMQDefaultPass: "FiapAdmin@123"
  rabbitMQDefaultVHost: "/"
  rabbitMQDefaultHost: "https://b-ea5d81d0-c531-43a3-9bb6-44d43eea6f19.mq.us-east-2.on.aws"